// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bujsoynowkhsicrztegn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1anNveW5vd2toc2ljcnp0ZWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjgwNTYsImV4cCI6MjA3MzM0NDA1Nn0.whwme878RuB1XmVXd3uUeEu-eXKSksBrlPdT5Jy-h5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});